avro: Escape invalid UTF-8 strings when encoding
AVRO strings are to be encoded in UTF-8 according to the spec. We ran into a situation where customer data contained invalid UTF-8 strings, and so in order to conform to the AVRO spec and not confuse consumers, we need to escape invalid byte sequences.

`String::from_utf8_lossy()` will replace any invalid UTF-8 sequences with `U+FFFD REPLACEMENT CHARACTER`, which looks like this: �

Without the change to `maybe_encode()`, this test fails as expected with the following, proving that we were previously passing through invalid UTF-8:
```
---- encode::test::test_malformed_utf8_string stdout ----

thread 'encode::test::test_malformed_utf8_string' panicked at crates/avro/src/encode.rs:479:18:
called `Result::unwrap()` on an `Err` value: Invalid utf-8 string: incomplete utf-8 byte sequence from index 5
```