Automatically fetch collections for TS generation
Fixes #862

Teaches the `typescript generate` subcommand to automatically fetch
collections that are used as transform sources. This allows users to
create derivations of source collections without needing to first
pull their specs. Specs will be resolved by making a separate request
for collection that's named as the `source` of a transform but not
already included in the sources. I used a separate request per
collection because it simplifies the process of generating good error
messages, and because the number of collections to be fetched is
expected to be relatively small. An example error message is:

```
Error: resolving the collection 'estuary/public/wikipedia/recentchangess', referenced from the transform 'fromWiki' in derivation 'phil/test/wikipedia/test-derivation'

Caused by:
    the collection does not exist or you do not have access to it
```

I also updated `typescript generate` to use the same `SourceArgs` as
other commands. A minor related change is that the `flow_generated`
directory is now always placed relative to the current working directory
instead of within the direct parent of the `--source` argument.
This plays nicer with the common `SourceArgs` wich allow passing
multiple `--source` arguments.