connector_proxy: Include reason when 'check' subcommand fails
An Airbyte connector returning a well-formed connection status [1]
of 'FAILED' currently turns into an unhelpful error like:

    {"timestamp":"2022-09-21T21:36:40.118112447Z","level":"ERROR","message":"Check failed"}
    Error: go.estuary.dev/E008: IO Error
    Caused by:
        go.estuary.dev/E018: Connector's connection status is not successful

This commit makes that description a little bit more helpful and
also includes the 'message' text that the connector provides, so
the error might instead look something like:

    {"timestamp":"2022-09-21T21:36:40.118112447Z","level":"ERROR","message":"Check failed"}
    Error: go.estuary.dev/E008: IO Error
    Caused by:
        go.estuary.dev/E018: Connection failed: User 'wgd' not authorized

(Where the "User 'wgd' not authorized" bit is a hypothetical message
that might come from the underlying connector which would tell the user
what's actually gone wrong)

It would be nice to additionally remove the whole 'IO Error' wrapping
thing, but the plumbing for that is a bit complicated so I figured that
I ought to just tackle the easy part here.

[1] https://docs.airbyte.com/understanding-airbyte/airbyte-protocol#airbyteconnectionstatus-message